# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: BSD-2-Clause

include:
  - project: sysadmin/ci-utilities
    file:
      - /gitlab-templates/linux.yml
      - /gitlab-templates/freebsd.yml
      - /gitlab-templates/windows.yml
      - /gitlab-templates/reuse-lint.yml

